// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickLook.RelationalDbService.Entities;

namespace QuickLook.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190604204724_AddedBookmarkUserRelationship")]
    partial class AddedBookmarkUserRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QuickLook.RelationalDbService.Entities.Bookmark", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("ElasticsearchId");

                    b.Property<string>("Language");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bookmark");
                });

            modelBuilder.Entity("QuickLook.RelationalDbService.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("PasswordHash")
                        .IsRequired();

                    b.Property<string>("Salt")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");

                    b.HasAlternateKey("Username");

                    b.ToTable("User");
                });

            modelBuilder.Entity("QuickLook.RelationalDbService.Entities.Bookmark", b =>
                {
                    b.HasOne("QuickLook.RelationalDbService.Entities.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
